title: Ricardo Gemignani
description: Data Platform Consultant & Engineering Leader
url: https://ricksaarge.github.io
baseurl: ""

author:
  name: Ricardo Gemignani
  email: ricardo@gemin.us
  location: Minneapolis, MN

social:
  github: ricksaarge
  linkedin: ricksaarge
  medium: ricksaarge

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
